### ISSUE TITLE
0it [00:00, ?it/s] - nothing more

### ISSUE THREAD

**Issue by Raprodent** [sigsep/sigsep-mus-io#1]
Hey, I'm new to this, but have done everything as long as the guides go - decoded the STEM databases etc.
When I try to run the command
python IRM.py --eval_dir ./Evaluation_Dir --audio_dir ./Audio_Dir
it simply yields the result: 0it [00:00, ?it/s]
Then it returns to "base".

Any help highly appreciated, thanks! :)

**Comment by faroit** [comment]
Hi, sorry for the late reply.

I guess your questions is related to the code in the [oracle repository](https://github.com/sigsep/sigsep-mus-oracle).  Here, it is important to enable the decoded wav flag of the musdb parser. See [here](https://github.com/sigsep/sigsep-mus-db#use-a-decoded-version). I hope that solves the problem.

**Comment by Raprodent** [comment]
Hey mate, no worries. The oracle program is just for the stem.mp4's and not
for other audio files?
Merry Xmas!

**Comment by faroit** [comment]
Exactly, so you just need to add the `is_wav` flag

**Comment by Raprodent** [comment]
Do you have any insight in which vocal separator that currently work best?
:)

**Comment by faroit** [comment]
Have a look at the [SiSEC2018 results](https://sisec18.unmix.app/#/results/vocals/SDR) the best performing system from Sony is not open source, but you find a reference to reimplement it yourself [here](https://sisec18.unmix.app/#/methods/TAK2). We are currently developing an open source separation tool that will be released very soon in the next weeks. You can find more information about it [here](https://sigsep.github.io/tutorials/#music-source-separation-with-dnns-making-it-work)
