### ISSUE TITLE
error in “Encode SIGSEP MUS to STEMS format ”

### ISSUE THREAD

**Issue by weimisa341** [sigsep/sigsep-mus-io#2]
command line should be:
docker run --rm -v $(~)/data/ESTIMATE_DIR:/data faroit/sigsep-mus-io /scripts/encode.sh

**Comment by faroit** [comment]
thanks for that comment, do you want to make a pull request?

**Comment by Raprodent** [comment]
Uh I've already forgotten what this is. Can u help me setup?

**Comment by faroit** [comment]
no problem, I just fixed it myself. thanks again

**Comment by Raprodent** [comment]
Can u help me I have coffee for u
